### ISSUE TITLE
Thank you for this great prpject

### ISSUE THREAD

**Issue by emreakay** [recp/rays#1]
i like that repo :+1: 

we are looking forward to seeing new release as soon as possible.

**Comment by recp** [comment]
Hi @emreakay 

This will use [Universal Shading Language](http://github.com/UniversalShading) and its **VM** for both CPU and GPU shading. Also, probably will be integrated to [Graphics Kernel](https://github.com/recp/gk) or may stay sepate...

Curently sources ( [Universal Shading Language](http://github.com/UniversalShading),  [Physics Engine](https://github.com/recp/phy), ...) are private I may make them public in the future...

Thanks
